package bundled

import (
	"context"
	"encoding/json"
	"math"
	"os"
	"strings"
	"testing"
)

// goldens.json is generated by lab/make_goldens.py from the reference
// Hugging Face implementation. Token ids must match exactly; embeddings
// must match within float tolerance.
type goldenFile struct {
	Cases []struct {
		Text      string    `json:"text"`
		IDs       []int32   `json:"ids"`
		Embedding []float32 `json:"embedding"`
	} `json:"cases"`
}

func loadGoldens(t *testing.T) goldenFile {
	t.Helper()
	raw, err := os.ReadFile("testdata/goldens.json")
	if err != nil {
		t.Fatalf("reading goldens (generate with lab/make_goldens.py): %v", err)
	}
	var g goldenFile
	if err := json.Unmarshal(raw, &g); err != nil {
		t.Fatalf("parsing goldens: %v", err)
	}
	if len(g.Cases) == 0 {
		t.Fatal("goldens.json has no cases")
	}
	return g
}

func newTestTokenizer(t *testing.T) *tokenizer {
	t.Helper()
	tok, err := newTokenizer(strings.NewReader(vocabData))
	if err != nil {
		t.Fatalf("newTokenizer: %v", err)
	}
	return tok
}

func TestTokenizerMatchesReference(t *testing.T) {
	tok := newTestTokenizer(t)
	for _, c := range loadGoldens(t).Cases {
		name := c.Text
		if len(name) > 40 {
			name = name[:40] + "…"
		}
		t.Run(name, func(t *testing.T) {
			got := tok.encode(c.Text)
			if len(got) != len(c.IDs) {
				t.Fatalf("got %d ids, want %d\ngot:  %v\nwant: %v",
					len(got), len(c.IDs), got, c.IDs)
			}
			for i := range got {
				if got[i] != c.IDs[i] {
					t.Fatalf("id mismatch at %d: got %d, want %d\ngot:  %v\nwant: %v",
						i, got[i], c.IDs[i], got, c.IDs)
				}
			}
		})
	}
}

func TestTokenizerEdgeCases(t *testing.T) {
	tok := newTestTokenizer(t)
	tests := []struct {
		name, text string
		want       []int32 // nil means "just [CLS] [SEP]"
	}{
		{"empty", "", nil},
		{"whitespace only", " \t\n  ", nil},
		{"control chars only", "\x00\x7f", nil},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := tok.encode(tt.text)
			want := append(append([]int32{tok.cls}, tt.want...), tok.sep)
			if len(got) != len(want) {
				t.Fatalf("got %v, want %v", got, want)
			}
			for i := range got {
				if got[i] != want[i] {
					t.Fatalf("got %v, want %v", got, want)
				}
			}
		})
	}

	t.Run("very long word becomes UNK", func(t *testing.T) {
		got := tok.encode(strings.Repeat("a", 200))
		if len(got) != 3 || got[1] != tok.unk {
			t.Fatalf("got %v, want [CLS] [UNK] [SEP]", got)
		}
	})

	t.Run("truncates to maxSeqLen", func(t *testing.T) {
		got := tok.encode(strings.Repeat("word ", 1000))
		if len(got) != maxSeqLen {
			t.Fatalf("got %d tokens, want %d", len(got), maxSeqLen)
		}
		if got[len(got)-1] != tok.sep {
			t.Fatal("truncated sequence must still end with [SEP]")
		}
	})
}

// loadModel skips when the weight file is absent (fresh clone without
// hack/fetch-model.sh) so `go test ./...` stays green everywhere.
func loadModel(t testing.TB) *Bundled {
	t.Helper()
	if len(embeddedWeights) == 0 {
		if _, err := os.Stat("model.safetensors"); err != nil {
			t.Skip("model.safetensors not present; run hack/fetch-model.sh")
		}
		t.Setenv("HAYPILE_MODEL_PATH", "model.safetensors")
	}
	b, err := New()
	if err != nil {
		t.Fatalf("New: %v", err)
	}
	return b
}

func TestEmbedMatchesReference(t *testing.T) {
	b := loadModel(t)
	g := loadGoldens(t)

	texts := make([]string, len(g.Cases))
	for i, c := range g.Cases {
		texts[i] = c.Text
	}
	got, err := b.Embed(context.Background(), texts)
	if err != nil {
		t.Fatalf("Embed: %v", err)
	}

	const tol = 2e-4 // fp32 accumulation-order differences across impls
	for i, c := range g.Cases {
		if len(got[i]) != hiddenDim {
			t.Fatalf("case %d: got %d dims, want %d", i, len(got[i]), hiddenDim)
		}
		var maxDiff float64
		for j := range c.Embedding {
			d := math.Abs(float64(got[i][j] - c.Embedding[j]))
			if d > maxDiff {
				maxDiff = d
			}
		}
		if maxDiff > tol {
			t.Errorf("case %d (%.40q): max |diff| = %g > %g", i, c.Text, maxDiff, tol)
		}
	}
}

func TestEmbedVectorsAreNormalized(t *testing.T) {
	b := loadModel(t)
	vecs, err := b.Embed(context.Background(), []string{"hello world"})
	if err != nil {
		t.Fatalf("Embed: %v", err)
	}
	var sum float64
	for _, x := range vecs[0] {
		sum += float64(x) * float64(x)
	}
	if math.Abs(sum-1) > 1e-5 {
		t.Fatalf("‖v‖² = %g, want 1", sum)
	}
}

func TestEmbedSemanticSanity(t *testing.T) {
	// The M1 definition of done: "agreement cancellation" is closer to
	// "termination clauses" than to unrelated text.
	b := loadModel(t)
	vecs, err := b.Embed(context.Background(), []string{
		"agreement cancellation",
		"This contract may be terminated by either party with written notice.",
		"The recipe calls for two cups of flour and a pinch of salt.",
	})
	if err != nil {
		t.Fatalf("Embed: %v", err)
	}
	dot := func(a, b []float32) float64 {
		var s float64
		for i := range a {
			s += float64(a[i]) * float64(b[i])
		}
		return s
	}
	related, unrelated := dot(vecs[0], vecs[1]), dot(vecs[0], vecs[2])
	if related <= unrelated {
		t.Fatalf("semantic ordering wrong: related %.4f ≤ unrelated %.4f", related, unrelated)
	}
}

func TestEmbedEmptyBatch(t *testing.T) {
	b := loadModel(t)
	got, err := b.Embed(context.Background(), nil)
	if err != nil || len(got) != 0 {
		t.Fatalf("got %v, %v; want empty, nil", got, err)
	}
}

func TestEmbedCancelledContext(t *testing.T) {
	b := loadModel(t)
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	texts := make([]string, 64)
	for i := range texts {
		texts[i] = "some text to embed"
	}
	if _, err := b.Embed(ctx, texts); err == nil {
		t.Fatal("want context error for cancelled batch")
	}
}

func BenchmarkEmbedChunk(b *testing.B) {
	m := loadModel(b)
	// A representative ~400-token chunk, the indexing unit.
	chunk := strings.Repeat("The parties agree that termination requires thirty days written notice. ", 40)
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		if _, err := m.Embed(context.Background(), []string{chunk}); err != nil {
			b.Fatal(err)
		}
	}
}

func BenchmarkEmbedQuery(b *testing.B) {
	m := loadModel(b)
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		if _, err := m.Embed(context.Background(), []string{"what does the contract say about termination?"}); err != nil {
			b.Fatal(err)
		}
	}
}
